[links]
# Componentes base de la URL
base_url = https://www.timeshighereducation.com/world-university-rankings/2025
# Links
path_wr = world-ranking
path_cs = subject-ranking/computer-science
path_en = subject-ranking/engineering-and-it

[subject-params]
# Parámetros exclusivos para links subjects
base = #!/length/-1/sort_by/rank/sort_order/asc/cols
scrs = scores
stts = stats

[scrs]
scrs_titles = rank, name, country, overall_score, research_qlt_score, industry_score, intl_outlook_score, research_env_score, teaching_score
scrs_ws_wr = cell-rank css-.*, cell-name css-.*, cell-scores_overall css-.*, cell-scores_citations css-.*, cell-scores_industry_income css-.*, cell-scores_international_outlook css-.*, cell-scores_research css-.*, cell-scores_teaching css-.*
scrs_ws_su = rank sorting_1 sorting_2, name namesearch, scores overall-score, scores citations-score,  scores industry_income-score,  scores international_outlook-score, scores research-score, scores teaching-score

[stts]
stts_titles = rank, name, country, number_students, student_staff_ratio, intl_students, female_male_ratio
stts_ws_wr = cell-rank css-.*, cell-name css-.*, cell-stats_number_students css-.*, cell-stats_student_staff_ratio css-.*, cell-stats_pc_intl_students css-.*, cell-stats_female_male_ratio css-.*
stts_ws_su = rank sorting_1 sorting_2, name namesearch, stats stats_number_students, stats stats_student_staff_ratio, stats stats_pc_intl_students, stats stats_female_male_ratio
