[links]
# Componentes base de la URL
base_url = https://www.timeshighereducation.com/world-university-rankings/2025
# Rutas para los diferentes rankings
path_world_ranking = world-ranking
path_computer_science = subject-ranking/computer-science
path_engineering = subject-ranking/engineering-and-it
# Parametros comunes para queries
query_params_base = #!/length/-1/sort_by/rank/sort_order/asc/cols
query_params_scores = scores
query_params_stats = stats
# Cantidad de filas a filtrar
cant_univ = 100

[scores]
scores_titles = rank, name, overall_score, research_qlt_score, industry_score, intl_outlook_score, research_env_score, teaching_score
scores_ws = rank sorting_1 sorting_2, name namesearch, scores overall-score, scores citations-score,  scores industry_income-score,  scores international_outlook-score, scores research-score, scores teaching-score

[details]
details_titles = address, street_address, locality_address, region_address, postcode_address, country_address

[stats]
stats_titles = number_students, student_staff_ratio, intl_students, female_male_ratio
stats_ws = stats stats_number_students, stats stats_student_staff_ratio, stats stats_pc_intl_students, stats stats_female_male_ratio
